### ISSUE TITLE
Are source maps supported?

### ISSUE THREAD

**Issue by asfktz** [jedmao/craco-linaria#5]
Hi there,
Thank you for this plugin, it's really useful 🙏

I was wondering, did you manage to get the source-maps to work? 

The source-map is appended to the CSS file, but devtools doesn't recognize it.
I wonder if I did something wrong or maybe there is a bug?

I would appreciate you help (: 

**devtools, sourcemaps are not recognized**

![image](https://user-images.githubusercontent.com/199747/65381183-c5ca2100-dcf4-11e9-8e38-9ad2e7f7a0e3.png)

**src/.linaria_cache/src/App.linaria.css**
```
.Test_tm0as6w{font-size:3em;color:purple;}
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9Vc2Vycy9hZG1pbi9kZXYvbGluYS9zcmMvQXBwLmpzIl0sIm5hbWVzIjpbIi5UZXN0X3RtMGFzNnciXSwibWFwcGluZ3MiOiJBQUdNQSIsImZpbGUiOiIvVXNlcnMvYWRtaW4vZGV2L2xpbmEvc3JjL0FwcC5jc3MiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgUmVhY3QgZnJvbSAncmVhY3QnO1xuaW1wb3J0IHsgc3R5bGVkIH0gZnJvbSAnbGluYXJpYS9yZWFjdCc7XG5cbmNvbnN0IFRlc3QgPSBzdHlsZWQuZGl2YFxuICBmb250LXNpemU6IDNlbTtcbiAgY29sb3I6IHB1cnBsZTtcbmA7XG5cbmZ1bmN0aW9uIEFwcCgpIHtcbiAgcmV0dXJuIChcbiAgICA8ZGl2IGNsYXNzTmFtZT1cIkFwcFwiPlxuICAgICAgPFRlc3Q+XG4gICAgICAgIFRlc3RcbiAgICAgIDwvVGVzdD5cbiAgICA8L2Rpdj5cbiAgKTtcbn1cblxuZXhwb3J0IGRlZmF1bHQgQXBwO1xuIl19*/
```

**craco.config.js**
```js
module.exports = {
  plugins: [
    { plugin: require('craco-linaria') },
  ],
}
```

**linaria.config.js**
```js
module.exports = {
  displayName: true
}
```

**Example Repo**
https://github.com/asfktz/linaria-craco-no-sourcemap-demo

**Comment by jedmao** [comment]
I did not test this aspect of the plugin. Please, let me know your findings!

**Comment by elektronik2k5** [comment]
This works just fine for me with `react-scripts@4.0.3`, `linaria@2.1.0` and `craco-linaria@1.1.2`:
![image](https://user-images.githubusercontent.com/1078554/125983740-dc76aba2-cdae-40c3-8b82-08db651f62f5.png)

I think the issue can be closed.
